-- Listing 8-20

USE AdventureWorks2014; 
GO

CREATE DATABASE ENCRYPTION KEY
  WITH ALGORITHM = AES_128
  ENCRYPTION BY SERVER CERTIFICATE ServerCert; 
GO

ALTER DATABASE AdventureWorks2012
SET ENCRYPTION ON; 

GO
